version: '3.8'
services:
  frontend:
    build: ./permit-app-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./permit-app-backend
    ports:
      - "3001:3001"  
